/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type AboutImage = {
  image?: ImageImage;
  name?: string;
  role?: string;
  initials?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type GridSection = {
  _type: "gridSection";
  name?: string;
  sectionId?: string;
  theme?: "dark" | "white" | "cream";
  rows?: Array<
    {
      _key: string;
    } & GridRow
  >;
};

export type BookMeeting = {
  _type: "bookMeeting";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  subtitle?: string;
  calendlyUrl?: string;
};

export type Faq = {
  _type: "faq";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  subtitle?: string;
  items?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type FinalCta = {
  _type: "finalCta";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  sub?: string;
  primaryCta?: Cta;
  secondaryCta?: Cta;
  note?: string;
};

export type About = {
  _type: "about";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  lead?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: AboutImage;
  values?: Array<
    {
      _key: string;
    } & AboutValue
  >;
};

export type Pricing = {
  _type: "pricing";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  alignment?: "center" | "left";
  cards?: Array<
    {
      _key: string;
    } & PricingCard
  >;
  note?: string;
};

export type Scorecard = {
  _type: "scorecard";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  previewTitle?: string;
  previewBadge?: string;
  previewMetrics?: Array<
    {
      _key: string;
    } & ScorecardMetric
  >;
  imagePosition?: "left" | "right";
  features?: Array<
    {
      _key: string;
    } & ScorecardFeature
  >;
};

export type Results = {
  _type: "results";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  subtitle?: string;
  alignment?: "center" | "left";
  layout?: "split" | "stacked";
  metrics?: Array<
    {
      _key: string;
    } & ResultsMetric
  >;
  extraMetrics?: Array<
    {
      _key: string;
    } & ResultsExtraMetric
  >;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
};

export type Process = {
  _type: "process";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  alignment?: "center" | "left";
  layout?: "alternating" | "stacked";
  steps?: Array<
    {
      _key: string;
    } & ProcessStep
  >;
};

export type Solution = {
  _type: "solution";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  cards?: Array<
    {
      _key: string;
    } & SolutionCard
  >;
};

export type Problem = {
  _type: "problem";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  subtitle?: string;
  bigStat?: string;
  quote?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  statCards?: Array<
    {
      _key: string;
    } & ProblemStatCard
  >;
};

export type TrustBar = {
  _type: "trustBar";
  theme?: "dark" | "white" | "cream";
  items?: Array<
    {
      _key: string;
    } & TrustItem
  >;
};

export type Hero = {
  _type: "hero";
  theme?: "dark" | "white" | "cream";
  eyebrow?: string;
  headline?: string;
  headlineHighlight?: string;
  sub?: string;
  primaryCta?: Cta;
  secondaryCta?: Cta;
  stats?: Array<
    {
      _key: string;
    } & HeroStat
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navigation?: {
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    ctaLabel?: string;
    ctaHref?: string;
    theme?: "cream" | "dark";
  };
  footer?: {
    brandDescription?: string;
    socialLinks?: Array<
      {
        _key: string;
      } & SocialLink
    >;
    columns?: Array<
      {
        _key: string;
      } & FooterColumn
    >;
    legalLinks?: Array<
      {
        _key: string;
      } & FooterLink
    >;
    copyright?: string;
  };
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  canonicalUrl?: string;
  siteName?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo?: Seo;
  modules?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & TrustBar)
    | ({
        _key: string;
      } & Problem)
    | ({
        _key: string;
      } & Solution)
    | ({
        _key: string;
      } & Process)
    | ({
        _key: string;
      } & Results)
    | ({
        _key: string;
      } & Scorecard)
    | ({
        _key: string;
      } & Pricing)
    | ({
        _key: string;
      } & About)
    | ({
        _key: string;
      } & FinalCta)
    | ({
        _key: string;
      } & Faq)
    | ({
        _key: string;
      } & BookMeeting)
    | ({
        _key: string;
      } & GridSection)
  >;
};

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
  variant?: "primary" | "secondary";
  ctaType?: "internal" | "external" | "calendly";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type GridColumn = {
  _type: "gridColumn";
  width?: "auto" | "half" | "oneThird" | "twoThirds" | "full";
  verticalAlign?: "top" | "center" | "bottom";
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "eyebrow" | "subtitle" | "lead";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & StatCardsBlock)
    | ({
        _key: string;
      } & CtaBlock)
    | ({
        _key: string;
      } & TestimonialBlock)
    | ({
        _key: string;
      } & NumberedStepBlock)
    | ({
        _key: string;
      } & IconFeatureBlock)
    | ({
        _key: string;
      } & CheckListBlock)
  >;
};

export type GridRow = {
  _type: "gridRow";
  alignment?: "left" | "center";
  columns?: Array<
    {
      _key: string;
    } & GridColumn
  >;
};

export type CheckListBlock = {
  _type: "checkListBlock";
  lineSeparated?: boolean;
  items?: Array<{
    label?: string;
    _type: "checkListItem";
    _key: string;
  }>;
};

export type IconFeatureBlock = {
  _type: "iconFeatureBlock";
  items?: Array<
    {
      _key: string;
    } & IconFeature
  >;
};

export type NumberedStepBlock = {
  _type: "numberedStepBlock";
  items?: Array<
    {
      _key: string;
    } & NumberedStep
  >;
};

export type TestimonialBlock = {
  _type: "testimonialBlock";
  items?: Array<
    {
      _key: string;
    } & Testimonial
  >;
};

export type CtaBlock = {
  _type: "ctaBlock";
  items?: Array<
    {
      _key: string;
    } & Cta
  >;
  alignment?: "left" | "center";
};

export type StatCardsBlock = {
  _type: "statCardsBlock";
  theme?: "cream" | "white";
  columns?: 2 | 3 | 4;
  items?: Array<
    {
      _key: string;
    } & StatCard
  >;
};

export type IconFeature = {
  _type: "iconFeature";
  iconName?:
    | "phone"
    | "calendar"
    | "clock"
    | "check-circle"
    | "mail"
    | "users"
    | "bar-chart"
    | "shield"
    | "zap"
    | "star"
    | "bell"
    | "heart"
    | "globe"
    | "target"
    | "trending-up";
  title?: string;
  description?: string;
};

export type NumberedStep = {
  _type: "numberedStep";
  title?: string;
  description?: string;
};

export type StatCard = {
  _type: "statCard";
  icon?:
    | "phone-off"
    | "dollar-sign"
    | "users"
    | "clock"
    | "alert-circle"
    | "trending-down"
    | "trending-up"
    | "bar-chart"
    | "check-circle"
    | "star";
  value?: string;
  label?: string;
  compareText?: string;
  valueColor?: "navy" | "red" | "gold" | "teal";
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type ResultsExtraMetric = {
  _type: "resultsExtraMetric";
  label?: string;
  value?: string;
};

export type ResultsMetric = {
  _type: "resultsMetric";
  label?: string;
  industryValue?: string;
  industryBarWidth?: string;
  porterValue?: string;
  porterBarWidth?: string;
};

export type AboutValue = {
  _type: "aboutValue";
  title?: string;
  desc?: string;
};

export type PricingCard = {
  _type: "pricingCard";
  tag?: string;
  amount?: string;
  period?: string;
  desc?: string;
  features?: Array<string>;
  ctaLabel?: string;
  ctaHref?: string;
  variant?: "light" | "dark";
};

export type ScorecardMetric = {
  _type: "scorecardMetric";
  label?: string;
  value?: string;
  variant?: "default" | "gold" | "up" | "down";
};

export type ScorecardFeature = {
  _type: "scorecardFeature";
  icon?: "activity" | "users" | "pie-chart" | "monitor" | "bar-chart";
  title?: string;
  desc?: string;
};

export type Testimonial = {
  _type: "testimonial";
  quote?: string;
  author?: string;
  role?: string;
  avatar?: string;
};

export type ProcessStep = {
  _type: "processStep";
  tag?: string;
  title?: string;
  desc?: string;
};

export type SolutionCard = {
  _type: "solutionCard";
  icon?:
    | "phone"
    | "calendar"
    | "message-circle"
    | "pie-chart"
    | "shield"
    | "activity"
    | "users";
  title?: string;
  desc?: string;
};

export type ProblemStatCard = {
  _type: "problemStatCard";
  icon?:
    | "phone-off"
    | "dollar-sign"
    | "users"
    | "clock"
    | "alert-circle"
    | "trending-down";
  number?: string;
  color?: "red" | "amber" | "navy" | "teal";
  desc?: string;
};

export type TrustItem = {
  _type: "trustItem";
  icon?:
    | "shield"
    | "shield-check"
    | "globe"
    | "check-circle"
    | "star"
    | "phone"
    | "calendar"
    | "message-circle"
    | "bar-chart"
    | "users"
    | "clock";
  label?: string;
};

export type HeroStat = {
  _type: "heroStat";
  value?: string;
  suffix?: string;
  label?: string;
  barWidth?: string;
  barColor?: "gold" | "teal";
};

export type FooterColumn = {
  _type: "footerColumn";
  title?: string;
  links?: Array<
    {
      _key: string;
    } & FooterLink
  >;
};

export type SocialLink = {
  _type: "socialLink";
  platform?:
    | "linkedin"
    | "twitter"
    | "facebook"
    | "instagram"
    | "youtube"
    | "email";
  url?: string;
};

export type FooterLink = {
  _type: "footerLink";
  label?: string;
  href?: string;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  href?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AboutImage
  | SanityImageAssetReference
  | ImageImage
  | GridSection
  | BookMeeting
  | Faq
  | FinalCta
  | About
  | Pricing
  | Scorecard
  | Results
  | Process
  | Solution
  | Problem
  | TrustBar
  | Hero
  | SiteSettings
  | Seo
  | Page
  | Cta
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | GridColumn
  | GridRow
  | CheckListBlock
  | IconFeatureBlock
  | NumberedStepBlock
  | TestimonialBlock
  | CtaBlock
  | StatCardsBlock
  | IconFeature
  | NumberedStep
  | StatCard
  | FaqItem
  | ResultsExtraMetric
  | ResultsMetric
  | AboutValue
  | PricingCard
  | ScorecardMetric
  | ScorecardFeature
  | Testimonial
  | ProcessStep
  | SolutionCard
  | ProblemStatCard
  | TrustItem
  | HeroStat
  | FooterColumn
  | SocialLink
  | FooterLink
  | NavLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/queries.ts
// Variable: ALL_PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current) && slug.current != "home"] {    "slug": slug.current  }
export type ALL_PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    slug,    seo {      metaTitle,      metaDescription,      ogImage {        asset-> {          url,        },      },      canonicalUrl,      siteName,    },    modules[] {      _type,      _key,      ...,      stats[] {        ...,      },      statCards[] {        ...,      },      cards[] {        ...,      },      steps[] {        ...,      },      metrics[] {        ...,      },      extraMetrics[] {        ...,      },      testimonials[] {        ...,      },      previewMetrics[] {        ...,      },      features[] {        ...,      },      values[] {        ...,      },      image {        ...,        asset->,      },      primaryCta {        ...,      },      secondaryCta {        ...,      },      rows[] {        ...,        columns[] {          ...,          content[] {            ...,            _type == "image" => { ..., asset-> }          }        }      },    }  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    canonicalUrl: string | null;
    siteName: string | null;
  } | null;
  modules: Array<
    | {
        _type: "about";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        titleHighlight?: string;
        lead?: string;
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        image: {
          image?: ImageImage;
          name?: string;
          role?: string;
          initials?: string;
          asset: null;
        } | null;
        values: Array<{
          _key: string;
          _type: "aboutValue";
          title?: string;
          desc?: string;
        }> | null;
        stats: null;
        statCards: null;
        cards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
    | {
        _type: "bookMeeting";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        subtitle?: string;
        calendlyUrl?: string;
        stats: null;
        statCards: null;
        cards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
    | {
        _type: "faq";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        subtitle?: string;
        items?: Array<
          {
            _key: string;
          } & FaqItem
        >;
        stats: null;
        statCards: null;
        cards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
    | {
        _type: "finalCta";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        titleHighlight?: string;
        sub?: string;
        primaryCta: {
          _type: "cta";
          label?: string;
          href?: string;
          variant?: "primary" | "secondary";
          ctaType?: "calendly" | "external" | "internal";
        } | null;
        secondaryCta: {
          _type: "cta";
          label?: string;
          href?: string;
          variant?: "primary" | "secondary";
          ctaType?: "calendly" | "external" | "internal";
        } | null;
        note?: string;
        stats: null;
        statCards: null;
        cards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        rows: null;
      }
    | {
        _type: "gridSection";
        _key: string;
        name?: string;
        sectionId?: string;
        theme?: "cream" | "dark" | "white";
        rows: Array<{
          _key: string;
          _type: "gridRow";
          alignment?: "center" | "left";
          columns: Array<{
            _key: string;
            _type: "gridColumn";
            width?: "auto" | "full" | "half" | "oneThird" | "twoThirds";
            verticalAlign?: "bottom" | "center" | "top";
            content: Array<
              | {
                  children?: Array<{
                    marks?: Array<string>;
                    text?: string;
                    _type: "span";
                    _key: string;
                  }>;
                  style?:
                    | "eyebrow"
                    | "h1"
                    | "h2"
                    | "h3"
                    | "lead"
                    | "normal"
                    | "subtitle";
                  listItem?: "bullet" | "number";
                  markDefs?: Array<{
                    href?: string;
                    _type: "link";
                    _key: string;
                  }>;
                  level?: number;
                  _type: "block";
                  _key: string;
                }
              | {
                  _key: string;
                  _type: "checkListBlock";
                  lineSeparated?: boolean;
                  items?: Array<{
                    label?: string;
                    _type: "checkListItem";
                    _key: string;
                  }>;
                }
              | {
                  _key: string;
                  _type: "ctaBlock";
                  items?: Array<
                    {
                      _key: string;
                    } & Cta
                  >;
                  alignment?: "center" | "left";
                }
              | {
                  _key: string;
                  _type: "iconFeatureBlock";
                  items?: Array<
                    {
                      _key: string;
                    } & IconFeature
                  >;
                }
              | {
                  asset: {
                    _id: string;
                    _type: "sanity.imageAsset";
                    _createdAt: string;
                    _updatedAt: string;
                    _rev: string;
                    originalFilename?: string;
                    label?: string;
                    title?: string;
                    description?: string;
                    altText?: string;
                    sha1hash?: string;
                    extension?: string;
                    mimeType?: string;
                    size?: number;
                    assetId?: string;
                    uploadId?: string;
                    path?: string;
                    url?: string;
                    metadata?: SanityImageMetadata;
                    source?: SanityAssetSourceData;
                  } | null;
                  media?: unknown;
                  hotspot?: SanityImageHotspot;
                  crop?: SanityImageCrop;
                  _type: "image";
                  _key: string;
                }
              | {
                  _key: string;
                  _type: "numberedStepBlock";
                  items?: Array<
                    {
                      _key: string;
                    } & NumberedStep
                  >;
                }
              | {
                  _key: string;
                  _type: "statCardsBlock";
                  theme?: "cream" | "white";
                  columns?: 2 | 3 | 4;
                  items?: Array<
                    {
                      _key: string;
                    } & StatCard
                  >;
                }
              | {
                  _key: string;
                  _type: "testimonialBlock";
                  items?: Array<
                    {
                      _key: string;
                    } & Testimonial
                  >;
                }
            > | null;
          }> | null;
        }> | null;
        stats: null;
        statCards: null;
        cards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
      }
    | {
        _type: "hero";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        headline?: string;
        headlineHighlight?: string;
        sub?: string;
        primaryCta: {
          _type: "cta";
          label?: string;
          href?: string;
          variant?: "primary" | "secondary";
          ctaType?: "calendly" | "external" | "internal";
        } | null;
        secondaryCta: {
          _type: "cta";
          label?: string;
          href?: string;
          variant?: "primary" | "secondary";
          ctaType?: "calendly" | "external" | "internal";
        } | null;
        stats: Array<{
          _key: string;
          _type: "heroStat";
          value?: string;
          suffix?: string;
          label?: string;
          barWidth?: string;
          barColor?: "gold" | "teal";
        }> | null;
        statCards: null;
        cards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        rows: null;
      }
    | {
        _type: "pricing";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        titleHighlight?: string;
        subtitle?: string;
        alignment?: "center" | "left";
        cards: Array<{
          _key: string;
          _type: "pricingCard";
          tag?: string;
          amount?: string;
          period?: string;
          desc?: string;
          features?: Array<string>;
          ctaLabel?: string;
          ctaHref?: string;
          variant?: "dark" | "light";
        }> | null;
        note?: string;
        stats: null;
        statCards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
    | {
        _type: "problem";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        titleHighlight?: string;
        subtitle?: string;
        bigStat?: string;
        quote?: string;
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        statCards: Array<{
          _key: string;
          _type: "problemStatCard";
          icon?:
            | "alert-circle"
            | "clock"
            | "dollar-sign"
            | "phone-off"
            | "trending-down"
            | "users";
          number?: string;
          color?: "amber" | "navy" | "red" | "teal";
          desc?: string;
        }> | null;
        stats: null;
        cards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
    | {
        _type: "process";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        titleHighlight?: string;
        subtitle?: string;
        alignment?: "center" | "left";
        layout?: "alternating" | "stacked";
        steps: Array<{
          _key: string;
          _type: "processStep";
          tag?: string;
          title?: string;
          desc?: string;
        }> | null;
        stats: null;
        statCards: null;
        cards: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
    | {
        _type: "results";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        subtitle?: string;
        alignment?: "center" | "left";
        layout?: "split" | "stacked";
        metrics: Array<{
          _key: string;
          _type: "resultsMetric";
          label?: string;
          industryValue?: string;
          industryBarWidth?: string;
          porterValue?: string;
          porterBarWidth?: string;
        }> | null;
        extraMetrics: Array<{
          _key: string;
          _type: "resultsExtraMetric";
          label?: string;
          value?: string;
        }> | null;
        testimonials: Array<{
          _key: string;
          _type: "testimonial";
          quote?: string;
          author?: string;
          role?: string;
          avatar?: string;
        }> | null;
        stats: null;
        statCards: null;
        cards: null;
        steps: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
    | {
        _type: "scorecard";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        titleHighlight?: string;
        subtitle?: string;
        previewTitle?: string;
        previewBadge?: string;
        previewMetrics: Array<{
          _key: string;
          _type: "scorecardMetric";
          label?: string;
          value?: string;
          variant?: "default" | "down" | "gold" | "up";
        }> | null;
        imagePosition?: "left" | "right";
        features: Array<{
          _key: string;
          _type: "scorecardFeature";
          icon?: "activity" | "bar-chart" | "monitor" | "pie-chart" | "users";
          title?: string;
          desc?: string;
        }> | null;
        stats: null;
        statCards: null;
        cards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
    | {
        _type: "solution";
        _key: string;
        theme?: "cream" | "dark" | "white";
        eyebrow?: string;
        title?: string;
        titleHighlight?: string;
        subtitle?: string;
        cards: Array<{
          _key: string;
          _type: "solutionCard";
          icon?:
            | "activity"
            | "calendar"
            | "message-circle"
            | "phone"
            | "pie-chart"
            | "shield"
            | "users";
          title?: string;
          desc?: string;
        }> | null;
        stats: null;
        statCards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
    | {
        _type: "trustBar";
        _key: string;
        theme?: "cream" | "dark" | "white";
        items?: Array<
          {
            _key: string;
          } & TrustItem
        >;
        stats: null;
        statCards: null;
        cards: null;
        steps: null;
        metrics: null;
        extraMetrics: null;
        testimonials: null;
        previewMetrics: null;
        features: null;
        values: null;
        image: null;
        primaryCta: null;
        secondaryCta: null;
        rows: null;
      }
  > | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0] {    navigation {      links[] {        label,        href,      },      ctaLabel,      ctaHref,      theme,    },    footer {      brandDescription,      socialLinks[] {        platform,        url,      },      columns[] {        title,        links[] {          label,          href,        },      },      legalLinks[] {        label,        href,      },      copyright,    },    seo {      metaTitle,      metaDescription,      ogImage {        asset-> {          url,        },      },      siteName,    },  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      navigation: null;
      footer: null;
      seo: null;
    }
  | {
      navigation: null;
      footer: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogImage: {
          asset: {
            url: string | null;
          } | null;
        } | null;
        siteName: string | null;
      } | null;
    }
  | {
      navigation: {
        links: Array<{
          label: string | null;
          href: string | null;
        }> | null;
        ctaLabel: string | null;
        ctaHref: string | null;
        theme: "cream" | "dark" | null;
      } | null;
      footer: {
        brandDescription: string | null;
        socialLinks: Array<{
          platform:
            | "email"
            | "facebook"
            | "instagram"
            | "linkedin"
            | "twitter"
            | "youtube"
            | null;
          url: string | null;
        }> | null;
        columns: Array<{
          title: string | null;
          links: Array<{
            label: string | null;
            href: string | null;
          }> | null;
        }> | null;
        legalLinks: Array<{
          label: string | null;
          href: string | null;
        }> | null;
        copyright: string | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogImage: {
          asset: {
            url: string | null;
          } | null;
        } | null;
        siteName: string | null;
      } | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "page" && defined(slug.current) && slug.current != "home"] {\n    "slug": slug.current\n  }\n': ALL_PAGE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage {\n        asset-> {\n          url,\n        },\n      },\n      canonicalUrl,\n      siteName,\n    },\n    modules[] {\n      _type,\n      _key,\n      ...,\n      stats[] {\n        ...,\n      },\n      statCards[] {\n        ...,\n      },\n      cards[] {\n        ...,\n      },\n      steps[] {\n        ...,\n      },\n      metrics[] {\n        ...,\n      },\n      extraMetrics[] {\n        ...,\n      },\n      testimonials[] {\n        ...,\n      },\n      previewMetrics[] {\n        ...,\n      },\n      features[] {\n        ...,\n      },\n      values[] {\n        ...,\n      },\n      image {\n        ...,\n        asset->,\n      },\n      primaryCta {\n        ...,\n      },\n      secondaryCta {\n        ...,\n      },\n      rows[] {\n        ...,\n        columns[] {\n          ...,\n          content[] {\n            ...,\n            _type == "image" => { ..., asset-> }\n          }\n        }\n      },\n    }\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0] {\n    navigation {\n      links[] {\n        label,\n        href,\n      },\n      ctaLabel,\n      ctaHref,\n      theme,\n    },\n    footer {\n      brandDescription,\n      socialLinks[] {\n        platform,\n        url,\n      },\n      columns[] {\n        title,\n        links[] {\n          label,\n          href,\n        },\n      },\n      legalLinks[] {\n        label,\n        href,\n      },\n      copyright,\n    },\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage {\n        asset-> {\n          url,\n        },\n      },\n      siteName,\n    },\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
