import {
  seo,
  navLink,
  cta,
  footerLink,
  socialLink,
  footerColumn,
  trustItem,
  testimonial,
  pricingCard,
  faqItem,
  pricingCardsBlock,
  statCard,
  numberedStep,
  iconFeature,
  statCardsBlock,
  ctaBlock,
  testimonialBlock,
  numberedStepBlock,
  iconFeatureBlock,
  checkListBlock,
  gridRow,
  gridColumn,
} from "./objects";
import { page, siteSettings } from "./documents/index";
import {
  trustBar,
  faq,
  bookMeeting,
  gridSection,
} from "./modules";

export const schemaTypes = [
  // Objects
  seo,
  navLink,
  cta,
  footerLink,
  socialLink,
  footerColumn,
  trustItem,
  testimonial,
  pricingCard,
  faqItem,
  // Grid section building blocks
  pricingCardsBlock,
  statCard,
  numberedStep,
  iconFeature,
  statCardsBlock,
  ctaBlock,
  testimonialBlock,
  numberedStepBlock,
  iconFeatureBlock,
  checkListBlock,
  gridRow,
  gridColumn,
  // Documents
  page,
  siteSettings,
  // Modules
  trustBar,
  faq,
  bookMeeting,
  gridSection,
];
